ALTER TABLE CUSTOMERS 
MODIFY Email VARCHAR(100) NOT NULL;
ALTER TABLE CUSTOMERS 
ADD CONSTRAINT UC_Email UNIQUE (Email);
ALTER TABLE CUSTOMERS 
ADD CONSTRAINT CHK_CustomerAge CHECK (Age > 0 AND Age < 120);
ALTER TABLE CUSTOMERS 
MODIFY FullName VARCHAR(100) NOT NULL;