CREATE TABLE CUSTOMERS (
    CustomerID INT PRIMARY KEY AUTO_INCREMENT,
    FullName VARCHAR(100) NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE ORDERS (
    OrderID INT PRIMARY KEY AUTO_INCREMENT,
    OrderDate DATETIME DEFAULT CURRENT_TIMESTAMP, 
    TotalAmount DECIMAL(19, 4) NOT NULL,
    CustomerID INT NOT NULL, -- Cột liên kết
        CONSTRAINT FK_CustomerOrder 
    FOREIGN KEY (CustomerID) REFERENCES CUSTOMERS(CustomerID)
);