CREATE TABLE PRODUCTS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT, 
    ProductName VARCHAR(150) NOT NULL, 
    Price DECIMAL(19, 4) NOT NULL DEFAULT 0.0000, 
    Description VARCHAR(1000),
    CreatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);